name: 'Contains labels'
description: 'Look for input labels in Pull Request'
inputs:
  requiredLabels:
    description: 'required labels'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
 